#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=12
#SBATCH --time=0:30:00
#SBATCH --partition=aws-rc
#SBATCH --output=job_%j.out.log
#SBATCH --error=job_%j.err.log
#SBATCH --job-name=bundle_bench_f128_04

export OMP_NUM_THREADS=12
export CUDA_VISIBLE_DEVICES=0,1,2,3
export CS_BENCH_MG_MERGE_BOTTOM_MAX_ROW_FACTOR=2
export CS_BENCH_MG_MAX_LEVEL_DEVICE=25

# Transport intra-noeud (CUDA IPC + mémoire partagée)
export UCX_TLS=sm,cuda_copy,cuda_ipc
export NCCL_UCX_TLS=rc_x,cuda_copy
export NCCL_UCX_RNDV_THRESH=0
export UCX_MEMTYPE_CACHE=n
export NCCL_COLLNET_ENABLE=0
export NCCL_PLUGIN_P2P=ucx
export NCCL_DEBUG=info
export NCCL_DEBUG_SUBSYS=NET
#export LD_LIBRARY_PATH=$HPX_HOME/nccl_rdma_sharp_plugin/lib/:$LD_LIBRARY_PATH

# Set working directory:

cd /home/rocky/damien/saturne-open-cases/BUNDLE/BENCH_F128_01/RESU/20250715-1104

# Run command:

bash ./run_solver "$@"

